### ISSUE TITLE
COPY … FROM only worked with absolute path

### ISSUE THREAD

**Issue by ferdinandsalis** [red-4/curious-moon#1]
```
COPY master_plan
FROM '[PATH TO DIRECTORY]/master_plan.csv' WITH DELIMITER ',' HEADER CSV;
```
I stumbled a bit with this. Using the relative path I got `No such file or directory`. Even though the docs state you can do [this](https://www.postgresql.org/docs/current/static/sql-copy.html). Things all worked when using the absolute path and so did using the `psql`’s `\copy`.

**Comment by ferdinandsalis** [comment]
I should have kept on reading ☺️. Thanks Dee. Using ${CURDIR} in the Makefile solves this nicely.

**Comment by robconery** [comment]
Yeah I think I edited a bit much on this; she does explain the absolute path necessity later on. I'll update the code.
