### ISSUE TITLE
cds.csv hasn't been cleaned

### ISSUE THREAD

**Issue by lorenseanstewart** [red-4/curious-moon#11]
On pp. 204-205 the note says various columns have been removed from `cda.csv`, but the csv in the data folder that comes with the book still has all of the columns and must be cleaned by the reader.

**Comment by adam-beck** [comment]
@robconery can this issue be prioritized when you make the fixes?

**Comment by adam-beck** [comment]
I tried using the `cut` command that was talked about in a previous chapter but for some reason it's only removing the columns from the first row and not the entire file.

What am I doing wrong here?

```
cut -d ','  -f 1-4,6,8,10,18,21-24,27,31,33 cda.csv
```

**Comment by adam-beck** [comment]
Alright for anybody looking how to fix this I ended up using `csvcut` from the [csvkit utility](). And let me add this was a much better experience than trying to use `cut`. You can list the column names and indices: `csvcut -n cda.csv`.

The command I ran was

```
csvcut -c 1-4,6,8,10,18,21-24,27,31,33 cda.csv > cda_fixed.csv
```

**Comment by coaxial** [comment]
@adam-beck editing the file by hand in libreoffice and deleting the columns manually from there, I also have less rows than in the screenshot.
I opened #40 before seeing your issue, and I'm also getting 387546 rows.

**Comment by robconery** [comment]
Cheers thanks it's fixed.
