### ISSUE TITLE
duplicate data in events after each make in 02-normalize/Makefile

### ISSUE THREAD

**Issue by yacitus** [red-4/curious-moon#13]
Each time I run `make clean && make` in 02-normalize, and then run the code in 04-bent_field/03-full_text.sql, I get another duplicate of each row:

     529227 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     529195 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     528980 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     529408 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     529567 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     529724 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     529870 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     530123 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     530045 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     373294 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     373066 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     373438 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     373175 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     373194 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     373483 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     373398 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     373336 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     373259 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
    (72 rows)

...run it again, and:

     588250 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     588369 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     588429 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     588298 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     587946 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     588717 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     588818 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     588011 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     588893 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     587790 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     414573 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414984 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414839 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414786 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414907 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414763 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414719 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414683 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414532 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     414618 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
    (80 rows)

Here is the output from `make clean && make`:

    psql enceladus -f /Users/dspitzer/dev/a_curious_moon/book_and_data/code_and_data/02-normalize/build.sql
    psql:/Users/dspitzer/dev/a_curious_moon/book_and_data/code_and_data/02-normalize/build.sql:1: NOTICE:  drop cascades to view enceladus_events
    DROP TABLE
    DROP TABLE
    DROP TABLE
    DROP TABLE
    DROP TABLE
    DROP TABLE
    DROP TABLE
    CREATE TABLE
    COPY 61873
    psql:/Users/dspitzer/dev/a_curious_moon/book_and_data/code_and_data/02-normalize/build.sql:23: NOTICE:  table "teams" does not exist, skipping
    DROP TABLE
    SELECT 14
    ALTER TABLE
    psql:/Users/dspitzer/dev/a_curious_moon/book_and_data/code_and_data/02-normalize/build.sql:33: NOTICE:  table "spass_types" does not exist, skipping
    DROP TABLE
    SELECT 5
    ALTER TABLE
    psql:/Users/dspitzer/dev/a_curious_moon/book_and_data/code_and_data/02-normalize/build.sql:43: NOTICE:  table "targets" does not exist, skipping
    DROP TABLE
    SELECT 46
    ALTER TABLE
    psql:/Users/dspitzer/dev/a_curious_moon/book_and_data/code_and_data/02-normalize/build.sql:54: NOTICE:  table "event_types" does not exist, skipping
    DROP TABLE
    SELECT 596
    ALTER TABLE
    psql:/Users/dspitzer/dev/a_curious_moon/book_and_data/code_and_data/02-normalize/build.sql:65: NOTICE:  table "requests" does not exist, skipping
    DROP TABLE
    SELECT 5092
    ALTER TABLE
    CREATE TABLE
    INSERT 0 618730

I guess this is happening because table "event_types" (among others) isn't getting dropped. But I can't figure out why.

**Comment by robconery** [comment]
My first thought is that the tables arent being dropped and reloaded. This should happen with the Schema bits and I can see that the drop I exists is skipping which means that nothing is being dropped first before everything else. 

Can you check build.sql and see if drops are happening?

**Comment by robconery** [comment]
Sorry on phone do formatting sucks

**Comment by yacitus** [comment]
I'm attaching the entire build.sql: 
[build.sql.zip](https://github.com/red-4/curious-moon/files/1619722/build.sql.zip)

The drops for several tables are in there multiple times, which I guess explains the 'NOTICE:  table "xxx" does not exist, skipping' messages.

Can you reproduce the problem?

**Comment by yacitus** [comment]
I ran `psql enceladus -f scripts/import.sql` from 02-normalize, then `psql enceladus` and did a `\dt`:

    enceladus=# \dt
                List of relations
     Schema |     Name     | Type  |  Owner
    --------+--------------+-------+----------
     public | master_plan  | table | dspitzer
     public | mission_plan | table | dspitzer
    (2 rows)

I then did:

    enceladus=# drop table master_plan;
    DROP TABLE
    enceladus=# drop table mission_plan;
    DROP TABLE
    enceladus=# \dt
    Did not find any relations.

I then did `make clean && make`, and once again ran the code in 04-bent_field/03-full_text.sql:

     646865 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     646832 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     647270 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     646561 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     647638 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     647327 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     647209 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     647914 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     647729 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     647200 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     646638 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     456055 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456412 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456425 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456423 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456241 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456339 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456227 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456142 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456187 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     456292 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     455991 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
    (88 rows)

Another duplicate of each row was created. So this happens even when I make sure all tables are dropped prior to the make.

Is there an index that needs to be deleted that isn't?

**Comment by yacitus** [comment]
I tried `psql enceladus -f scripts/import.sql` again:

    enceladus=# \dt
                List of relations
     Schema |    Name     | Type  |  Owner
    --------+-------------+-------+----------
     public | master_plan | table | dspitzer
    (1 row)

and I noticed "cascade" is missing from line 8 of import.sql: "drop table if exists master_plan;", so I tried:

    enceladus=# drop table if exists master_plan cascade;
    DROP TABLE
    enceladus=# \dt
    Did not find any relations.

But that didn't work:

     705303 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     706493 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     706572 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     705770 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     705936 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     705886 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     705734 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     706267 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     706522 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     706059 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     706140 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     706188 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     497876 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497889 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497392 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497690 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497637 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497425 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497711 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497836 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497767 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     498048 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497931 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
     497464 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
    (96 rows)

**Comment by robconery** [comment]
Thanks for all the effort you're putting into helping me solve this - appreciate it! I've been in Hawaii for a week and spent all day traveling, so I'm a bit out of it currently :). Is the summary of the problem that every time you run `make clean && make` that another row is appended into the `public.mission_plan` table?

I can see that you've verified that there are no tables - would you mind checking to be sure the `import` schema is empty too? I believe the table is loaded every time with `COPY` and that would append values in there.

**Comment by yacitus** [comment]
That was it. (The import schema.)

    enceladus=# \dt import.*
                List of relations
     Schema |    Name     | Type  |  Owner
    --------+-------------+-------+----------
     import | master_plan | table | dspitzer
    (1 row)

There is no `drop table if exists import.master_plan;` in 02-normalize/scripts/import.sql, nor is there a `create table import.master_plan`, so I added the following to the end of 02-normalize/scripts/import.sql (taken from page 37):

    create schema if not exists import;
    drop table if exists import.master_plan;
    create table import.master_plan(
      start_time_utc text,
      duration text,
      date text,
      team text,
      spass_type text,
      target text,
      request_name text,
      library_definition text,
      title text,
      description text
    );

And now when I run the code in 04-bent_field/03-full_text.sql I get:

      id   |    date    |                             title
    -------+------------+----------------------------------------------------------------
     19380 | 2005-02-16 | Enceladus rider (FP3 integration)
     58848 | 2005-02-16 | RSS Enceladus Gravity Thermal Stabilization
     19382 | 2005-02-16 | Enceladus rider (FP3 integration)
     18690 | 2005-02-17 | Enceladus FP1 and FP3 maps, high spectral resoluti
     14654 | 2005-02-17 | Enceladus rider (FP1,FP3 high spectral resolution integration)
     30307 | 2005-02-17 | Enceladus rider (FP1,FP3 coverage)
     58849 | 2005-02-17 | RSS Enceladus Gravity Thermal Stabilization
     41504 | 2005-02-17 | Enceladus rider (FP3 0.5 cm-1 res. integration)
    (8 rows)

...and continue to get it after each `make clean && make`.

**Comment by robconery** [comment]
Ahhh - yeah. I remember why this happened... originally I had "drop schema import cascade" on there, which will hose everything. Later on, however, I accidentally wiped out a 30M row table that made me a bit cranky :).

I like your solution, and yes a PR would be great. I'll amend the book as well. Really appreciate your help!

**Comment by yacitus** [comment]
I can't submit a pull request since the code repository is empty. But my changes are above.

**Comment by robconery** [comment]
Thanks again - this is fixed.
