### ISSUE TITLE
Unnecessary cast to date (A Bent Field -> Full Text Queries)

### ISSUE THREAD

**Issue by ruidfigueiredo** [red-4/curious-moon#15]
On the example (page 110, 123 in the pdf):

    select id, date, title
    from enceladus_events
    where date
    between '2005-02-01'::date
    and '2005-02-28'::date
    and search @@ to_tsquery('thermal');

The dates in the query are cast to date, i.e. '2005-02-01'::date and '2005-02-28'::date)

No where else is this done in the book (in the where clause of a query when the column is already date)

Just mentioning because it left me wondering if it was really required

**Comment by robconery** [comment]
Hmmm. Is it unnecessary? Are you sure that's a `date`? Yes, I see that a few pages prior the view was created with date as a `date` but will it always be that way? There's no harm in *ensuring* that something is cast as needed *especially* when your criteria demands it...
