### ISSUE TITLE
Small typo "files" -> fields (A Bent Field -> Using Materialized Views)

### ISSUE THREAD

**Issue by ruidfigueiredo** [red-4/curious-moon#17]
On page 159 (172 on the pdf) it says:

>At the very top of the file are all the changes made over the
>years to the result sets. Right there, in the middle, is the note that
>MJDATE was added, along with a few other **files**. Hmmm.

Instead of files, fields?

**Comment by adam-beck** [comment]
This is in the section 'Sniff The Sky' -> 'Using CSVSQL'

**Comment by robconery** [comment]
Fixed thanks!
