### ISSUE TITLE
In Orbit > Normalize - select from events table

### ISSUE THREAD

**Issue by adam-beck** [red-4/curious-moon#18]
In the "Normalize" section of the "In Orbit" chapter there are several select statements that involve the `events` table.

`select date from events limit 20;`
`select date::timestamptz from events;`

However, I can't get these queries to run. I don't see where the `events` table has a date field. Should this be pointed to the `import.master_plan` table instead?

**Comment by robconery** [comment]
Yeah... I should have been more clear on this :(. M. Sullivan has his own data set that he's using and... oh man long story there. I didn't *want* parity between the two as you were supposed to be doing Dee's work.

I can see why this is confusing. I'll fix this in a later rev.

**Comment by adam-beck** [comment]
Honestly that's how I felt when reading it because I wouldn't expect exact answers from my co-workers when I receive a question like this in real life. However, I kind of lost the connection with the character because Dee doesn't try this on her own machine even after getting the guidance.

I'm probably being picky. But, I love this concept you have ran with here!

**Comment by robconery** [comment]
I added a tweak to the text to hopefully point this out.
