### ISSUE TITLE
Page 82; M Yan?

### ISSUE THREAD

**Issue by adam-beck** [red-4/curious-moon#20]
In the letter from Mr. Sullivan to Dee:

> Data investigation is fun, isn’t it? Even though you’re querying it with what amounts to a hammer covered in broken glass and dog vomit. This is clean, structured, beautiful data, **M. Yan**, let’s treat it with some respect, shall we?

Probably should just use the name "Dee" instead of "M. Yan" in the first paragraph.

**Comment by robconery** [comment]
I don't understand.

**Comment by adam-beck** [comment]
I could be reading it wrong. But why is Mr. Sullivan talking (in an email) to Dee with a sentence like

> This is clean, structured, beautiful data, M. Yan, let's treat it with some respect, shall we?

Why is there an `M` if front of Dee's last name?

**Comment by robconery** [comment]
:) you'll have to read to find out...

**Comment by adam-beck** [comment]
So I just tried to cheat and did a search. I see now that I have read "M. Yan" several times without realizing it. Must've missed something unless you are using "M." as a general "Mr. Mrs. Ms." kind of thing.

**Comment by robconery** [comment]
It is revealed at the end :) no searching!
