### ISSUE TITLE
Running the Make file on Windows OS

### ISSUE THREAD

**Issue by stuarthillary** [red-4/curious-moon#21]
To successfully follow along with the book on Windows OS the user may need to install some tools (specifically cat), available in msys2 (http://www.msys2.org/). The path environment needs to include a pointer to those tools (e.g. C:\msys64\usr\bin). Once installed and set up, the makefile runs successfully.

**Comment by robconery** [comment]
Cheers. This is good stuff... but I don't know if it belongs in the issues. Would you be up for a PR maybe so I could pop in the README?
