### ISSUE TITLE
Making the Make file idempotent

### ISSUE THREAD

**Issue by stuarthillary** [red-4/curious-moon#22]
On page 33 it talks about making the SQL script idempotent i.e. running the SQL script multiple times will always give the same result.  I think a nice improvement would be to make the Make file itself idempotent. I have expanded my own make file to read as:

```makefile
DB=enceladus
BUILD=${CURDIR}/build.sql
SCRIPTS=${CURDIR}/scripts
CSV='${CURDIR}/data/master_plan.csv'
MASTER=$(SCRIPTS)/import.sql
NORMALIZE=$(SCRIPTS)/normalize.sql
USER=${USERNAME}

all: normalize
	createdb -U $(USER) $(DB)
	psql -U $(USER) -d $(DB) -f $(BUILD)

master:
	@cat $(MASTER) >> $(BUILD)

import: master
	@echo "COPY import.master_plan FROM $(CSV) WITH DELIMITER ',' HEADER CSV;" >> $(BUILD)

normalize: import
	@cat $(NORMALIZE) >> $(BUILD)

clean:
	@rm -rf $(BUILD)
	@dropdb -U $(USER) --if-exists $(DB)
````

This make file drops and recreates the database itself when using `make clean && make` . This also eliminates the manual step of creating the database before running the script for the very first time.

**Comment by robconery** [comment]
Interesting. How is this different from what's there currently? In other words: why is this more idempotent? Other than the drop/create DB bits?
