### ISSUE TITLE
Wrong join on page 60

### ISSUE THREAD

**Issue by danners** [red-4/curious-moon#26]
On the section where Dee discovers left joins, one join is not converted to a left join (event_types).

**Comment by robconery** [comment]
Thanks!

**Comment by idkjs** [comment]
Hi folks. Came across this same error:
```s
ERROR:  relation "event_types" does not exist
LINE 6:     INNER JOIN event_types ON event_types.description = impo...
```

Thinking through it, INNER JOIN is supposed to create a table then create a field description and assign `import.master_plan.library_definition` to it. 

So looks like event_types has not been created yet maybe. Is that the case? 

If i run `\d` in psql, i get:
```
               List of relations
 Schema |     Name      |   Type   |   Owner
--------+---------------+----------+-----------
 public | events        | table    | prisc_000
 public | events_id_seq | sequence | prisc_000
 public | master_plan   | table    | prisc_000
 public | teams         | table    | prisc_000
 public | teams_id_seq  | sequence | prisc_000
(5 rows)
```
Maybe I didn't create it?

New to all this. Thanks for any guidance.
