### ISSUE TITLE
Incorrect passage regarding query (Sniff the Sky ->Transforming Data with CTEs)

### ISSUE THREAD

**Issue by adam-beck** [red-4/curious-moon#27]
On page 176 Dee writes

> But what about the timestamp? How many of those will I get
> back? Here’s a sample run using the dates from that low flyby in
> March of 2010:

But the query is for October 2008. (year=2008, week=41)

```sql
select
time_stamp as nadir,
altitude
177Transforming Data with CTEs
from flyby_altitudes
where flyby_altitudes.altitude=28.576
and date_part(‘year’, time_stamp) = 2008
and date_part(‘week’, time_stamp) = 41;
```

**Comment by robconery** [comment]
Cheers thanks
