### ISSUE TITLE
File illustration different than file download 

### ISSUE THREAD

**Issue by bizarosteve** [red-4/curious-moon#3]
ZIP File illustration at the top of page 13, versus the files in the ZIP download:
- The zip file does not include the CDA/raw directory in the illustration
- The zip file includes a jpl_flybys.csv file at the root that I don't see in the illustration.  
Thanks.

**Comment by robconery** [comment]
These are not the same thing; which I can see would be a little confusing. The download that you have is for *you*. What Dee downloaded is an archive I put there for *her*. 

On one hand, parity would be a good idea, on the other it wouldn't make sense to include jpl_flybys.csv as she hasn't created it yet :).
