### ISSUE TITLE
Not taking advantage of index in Under The Ice -> Timestamps and Indexes

### ISSUE THREAD

**Issue by ruidfigueiredo** [red-4/curious-moon#30]
When defining the index this way (page 319):

```
create index concurrently idx_stamps
on inms.readings(time_stamp)
where altitude is not null;
```

The example query does not filter out the altitudes that are not null:

```
select * from inms.readings
where time_stamp > ‘2015-12-19 17:48:55.275’ and time_stamp < ‘2015-12-19 17:49:35.275’;
```

'explain select * from inms.readings where time_stamp > '2015-12-19 17:48:55.275' and time_stamp < '2015-12-19 17:49:35.275';' :

```
                                                                            QUERY PLAN                                                                             
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Gather  (cost=1000.00..222290.62 rows=1226 width=52)
   Workers Planned: 2
   ->  Parallel Seq Scan on readings  (cost=0.00..221168.02 rows=511 width=52)
         Filter: ((time_stamp > '2015-12-19 17:48:55.275'::timestamp without time zone) AND (time_stamp < '2015-12-19 17:49:35.275'::timestamp without time zone))

```

whereas with altitude is not null:

'explain select * from inms.readings where time_stamp > '2015-12-19 17:48:55.275' and time_stamp < '2015-12-19 17:49:35.275' and altitude is not null;`:

```
                                                                           QUERY PLAN                                                                            
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using idx_stamps on readings  (cost=0.43..25.29 rows=443 width=52)
   Index Cond: ((time_stamp > '2015-12-19 17:48:55.275'::timestamp without time zone) AND (time_stamp < '2015-12-19 17:49:35.275'::timestamp without time zone))


```

Also both `explain` outputs are very different from the examples on the book.

**Comment by coaxial** [comment]
Same observations here, to use a partial index you have to use the same predicates in your query otherwise Postgres won't use the partial index.

**Comment by robconery** [comment]
@ruidfigueiredo a partial index only applies to the criteria given. As the quote above it says:

>I want to restrict the indexing to only the values that I’ll be search- ing over, which are values with an altitude reading:

This is as intended and the index is being used... unless I misunderstand you?

**Comment by ruidfigueiredo** [comment]
Hi @robconery 

The use of a partial index is what I'm referring to. Here's the SQL from the book:

```
create index concurrently idx_stamps
on inms.readings(time_stamp)
where altitude is not null;
```

Query:

```
select * from inms.readings
where time_stamp > ‘2015-12-19 17:48:55.275’
and time_stamp < ‘2015-12-19 17:49:35.275’;
```

There's no `and altitude is not null` on the query. Shouldn't it be there to take advantage of the index?

**Comment by robconery** [comment]
Ah - got it thanks :). That would be confusing, yes.
