### ISSUE TITLE
Confusing description of exclusive bounds in the description of ranges (Under the ice/Advanced: Using Ranges, page 324)

### ISSUE THREAD

**Issue by ruidfigueiredo** [red-4/curious-moon#38]
The description of what is an exclusive upper and lower bound is a bit strange:

"If I had used () as an option the range would be exclusive,
meaning all dates between the upper and lower bound are considered the value"

**Comment by robconery** [comment]
What's the issue? You're confused about what those words mean? Or don't like my explanation?

**Comment by ruidfigueiredo** [comment]
I @robconery 

I usually love your explanations :)

Couldn't understand what this meant though. Here's the whole paragraph:

> 
> The [] option tells Postgres that this range is inclusive, meaning the upper and lower bounds of the range should be included. **If I had used () as an option the range would be exclusive,
> meaning all dates between the upper and lower bound are considered the value**. You can combine these two symbols as well. For instance, this: [) is a range that is inclusive on the lower bound, exclusive on the upper.
> 

I still don't understand what that sentence means. I did look at the documentation and I know that if () is used then the upper and lower bound dates are not part of the range. 

I just don't know how that sentence in bold conveys that.

I'm not a native speaker so this might be a failure from my part.

**Comment by robconery** [comment]
If I have a range, say `1,2,3,4` and I want to look at values between 1 and 4 I can do it exclusively, which would give me 2 and 3 (1 is the lower bound of the range, 4 is the upper) or inclusively, which would give me `1,2,3,4`.

Inclusive simply means "include the bounds". The bounds are the lowest and highest values in the range. Does this help?

**Comment by ruidfigueiredo** [comment]
Yes, that description is totally clear.

It was just the wording "are considered the value" that put me off, and the fact that we are talking about timestamps (and the word date is used as a timestamp).

Now that I know what it is it looks really obvious, but before it was confusing. I though there was a typo there.
