### ISSUE TITLE
S3 bucket not accessible, supplied cda.csv has extraneous columns, and other problems with SQL query

### ISSUE THREAD

**Issue by coaxial** [red-4/curious-moon#40]
p205, it says the columns containing placeholder data have been deleted from the `cda.csv` file on the S3 bucket. Since the bucket in not accessible, I've used the file at `/home/coaxial/Downloads/book_and_data/code_and_data/data/CDA/cda.csv`. This file does have the extra placeholder columns (and more), which causes an error[0] when imported with the SQL commands from pp205-206.

Attached is the CSV file without the placeholder columns that will work with the SQL statement on p205: 
[cda.csv.zip](https://github.com/red-4/curious-moon/files/1815961/cda.csv.zip)

I also noticed that the number of records doesn't match. The screenshot on p206 says `COPY 387546` records, but when I run it with the `cda.csv` file from above, I get `COPY 440510`. The screenshot also has a SET operation, but there isn't any in the statement on the previous page.

Finally, the statement is missing a `WITH`, i.e. it should be `WITH DELIMITER...`.

[0]: ` ERROR:  extra data after last expected column
CONTEXT:  COPY cda, line 2: "398120,2005-001T00:02:42,2453371.502,0,1,0,1,5.8E-15,1,0,1,-9.9E-99,1.3E-06,-9.9E-99,115.32,21.44,9....`

**Comment by robconery** [comment]
I'm closing this - please split this out and help me by providing the error you saw, what you expected, etc.

**Comment by robconery** [comment]
When you add issues and say "S3 is not accessible" - it would help if you told me what you tried to do. It helps as well to explain what you've done to get to the point you're at and so on.
