### ISSUE TITLE
Can't add primary key

### ISSUE THREAD

**Issue by coaxial** [red-4/curious-moon#41]
On p208, the query doesn't run because the column `id` already exists.

I found that this query works:

```sql
-- can't use the `add id serial primary key;` shorthand because the colum
-- already has an id column
create sequence cda.impacts_id_seq;
alter table cda.impacts
alter column id set default nextval('cda.impacts_id_seq');
alter table cda.impacts
add constraint impacts_pk primary key (id);
```
instead of
```sql
alter table cda.impacts
add id serial primary key;
```

**Comment by robconery** [comment]
Not responding; closing.

**Comment by Prosserc** [comment]
@robconery I believe that this is referring to the statement to create the `cda.impacts` table from this file:  https://github.com/red-4/curious-moon/blob/master/06-ring_dust/03-import_cda.sql.

I'm having the same issue, when you run the script (just updating the path to the csv file) you get a few errors, the last of which is the one referred to in this issue:

> ERROR:  column "id" of relation "impacts" already exists.

Not sure if you want to know about the other errors here as it is the same script, they are:

> ERROR:  missing data for column "impact_event_time"

This one seems to just be that the column name is `event_time` not `impact_event_time` (I believe that the manifest also uses the name that you used).

The next error is:

> ERROR:  missing data for column "impact_event_time"

I find that even if I correct the column name I still see this error (with the different col name) and it does not import any rows.

**Comment by robconery** [comment]
Ah - that would be due to not dropping the lookup tables first.
