### ISSUE TITLE
Missing `;`, `as`

### ISSUE THREAD

**Issue by coaxial** [red-4/curious-moon#45]
p287, the last line for the query should be `and alt-t is not null;`
pp289-290, both `inner join`s are missing `as`: `inner join time_altitudes ta` becomes `inner join time_altitdes as ta`. Same thing for the `min_times` join.

**Comment by robconery** [comment]
Please, show the SQL. I can't recognize page numbers as your device/font size/layout will be different then what I have here in front of me.

**Comment by coaxial** [comment]
My bad, I should have mentioned: the page numbers refer to the PDF version as they are printed in the bottom corners.

**Comment by robconery** [comment]
> the last line for the query should be and alt-t is not null;

The column name is `alt_t`. What makes you say otherwise?

> both inner joins are missing as

That's not valid SQL and the query runs fine. What version of PG are you running? Closing.
