### ISSUE TITLE
Issues in import of CDA data

### ISSUE THREAD

**Issue by Prosserc** [red-4/curious-moon#55]
When I run the script to import CDA data (https://github.com/red-4/curious-moon/blob/master/06-ring_dust/03-import_cda.sql) I get a few issues. I am just changing the path to the csv file. Here is the output:

>chris@postgres:~/cassini/curious_data$ psql enceladus < ./scripts/orig_cda.sql
Password:
DROP TABLE
CREATE TABLE
ERROR:  missing data for column "impact_event_time"
CONTEXT:  COPY cda, line 2: "398120     2005-001T00:02:42       2453371.502     0.00E+00        1       0.00E+00      1
        5.80E-15        1       0.00E+00        1       -9.90E-99       1.30E-06        ..."
DROP SCHEMA
CREATE SCHEMA
 id | time_stamp | impact_date | counter_number | sun_distance_au | saturn_distance_rads | x_velocity | y_velocity | z_velocity | particle_charge | particle_mass
----+------------+-------------+----------------+-----------------+----------------------+------------+------------+------------+-----------------+---------------
(0 rows)

> DROP SCHEMA
CREATE SCHEMA
SELECT 0
ERROR:  column "id" of relation "impacts" already exists

The issue at the bottom of the output for the id column was also raised here: https://github.com/red-4/curious-moon/issues/41, but closed due to lack of replies. I have added a comment to clarify. I will focus on the issue around the data not getting imported here (as indicated by `(0 rows)` in the output above.

I noticed the error message `ERROR:  missing data for column "impact_event_time"`. The cda_manifest.md file does list a column named `impact_event_time`, but in the header of cda.csv this is just called `EVENT_TIME`. I'm a little unsure whether this import statement was written for this version of the csv file as some of the other columns in the sql such as `particle_mass` and `particle_charge` do not seem to be headers in the csv.

I am getting the data from http://archive.redfour.io/cassini/cassini_data.zip, which is linked to in the update#1 version of the book (interestingly the issues fixed list includes "Fixed the cda.csv file to align with the statement in the book about it being cleaned (it wasn't)" which may be the same issue?

**Comment by robconery** [comment]
Crap. The problem is the CSV is *not* a CSV - it's a TAB file that I somehow put in place over the other, properly formatted CSV. Let me see if I can get to the bottom of this.

**Comment by robconery** [comment]
OK, I figured it out :). The *proper* CSV was overwritten for some reason, so I'm uploading the change right now. Should be up in about 20 minutes - sorry for the confusion! I ran (and reran) the queries here and all are good.
