### ISSUE TITLE
Text/Screenshot mismatch

### ISSUE THREAD

**Issue by lorenseanstewart** [red-4/curious-moon#9]
This is in regards to the data import and data casting that is the subject of pp. 53-55. In order to avoid the 'out of range' error, you import from *date* to *start_time_utc*. 

The use of *start_time_utc* column is shown in the screenshot on pg. 54, but it is not mentioned in the text. I didn't notice the change in the screenshot so I was stuck for a bit. 

Just a heads up.

**Comment by adam-beck** [comment]
Thank you! I was stuck on this as well.

**Comment by robconery** [comment]
Thanks Loren!
